#!/bin/bash
if [[ "$I2P" == "" ]] ; then
	echo '$I2P not set to java i2p root directory'
	exit 1
fi
jars=""
for j in $I2P/lib/*.jar ; do
	jars="$j:$jars"
done

java -cp "$jars" net.i2p.i2ptunnel.I2PTunnel -cli $1
